src/main/java/sparksoniq/JsoniqQueryExecutor.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
src/main/resources/test_files/runtime/EmptySeq.iq
src/main/resources/test_files/runtime/EmptySequence.iq
src/test/java/iq/RuntimeTests.java

Salvaged the approved implementation of VariableReferenceIterator along with its test.
Added improvements for handling of empty sequence as the final result for both the application and the test suite.

Variable reference iterator

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/control/SwitchRuntimeIterator.java
src/main/resources/test_files/runtime/ControlIterators/SwitchExpression1.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpression2.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpression3.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpressionError1.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpressionError2.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpressionError3.iq
src/main/resources/test_files/runtime/ControlIterators/SwitchExpressionError4.iq

Call next() without hasNext() check prevented in RunTimeIterator.
Switch statement type checking improved. Bug fixes applied.
Test cases added

Switch run time itr

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/arrays/ArrayFlattenFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/arrays/ArrayMembersFunctionIterator.java
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten2
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten2.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten5.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers1.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers2.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers3.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers4.iq
src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers5.iq

Remaining array related functions (**flatten** and **members**) are implemented with empty sequence support and lazy evaluation. Test cases added

Array fn iterators

---

src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/InstanceOfIterator.java
src/main/resources/test_files/runtime/InstanceOf.iq

https://github.com/Sparksoniq/sparksoniq/pull/46 solved Issue23 arithmetic, however didn't evaluate lazily. This problem has been fixed in this PR and the previous PR will be closed.

Instance of itr

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/arrays/ArrayFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectAccumulateFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectIntersectFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectRemoveKeysFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java

Unused function/variable definitions in array and object function iterators removed.
Performed simple cleanups for some iterators on error messages and variable definitions.

Cleanup empty seq sup

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
src/main/resources/test_files/runtime-spark/FunctionSequence/RDDFunctionCount.iq

RDD evaluation implemented for count operation, tests added
Edit: related issue: https://github.com/Sparksoniq/sparksoniq/issues/70

implement RDD ops for count, add tests

---

src/main/java/sparksoniq/exceptions/UnknownFunctionCallException.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
src/main/resources/test_files/runtime/FunctionCallError1.iq
src/main/resources/test_files/runtime/FunctionCallError2.iq

More informative alert messages for faulty function calls: https://github.com/Sparksoniq/sparksoniq/issues/93

Missing fn alerts

---

src/main/java/sparksoniq/JsoniqQueryExecutor.java
src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
src/main/resources/test_files/runtime-spark/RDDOutputFormat.iq

Issue #121 addressed.
The problem appeared to be only a serialization error.
Comments in parser-lexer files popped up again. I'll look into this next.

Rdd output formatting

---

src/main/java/sparksoniq/ShellStart.java
src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
src/main/java/sparksoniq/spark/iterator/SparkRuntimeIterator.java

A truncation warning has been placed. Addresses issue #137

Add truncation warning

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate3.iq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate4.iq

Issue #140 addressed. Test cases added

Fix 'only last element returned' bug

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/InsertBeforeFunctionIterator.java
src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove2.iq
src/main/resources/test_files/runtime/FunctionString/ConcatFunction2.iq
src/main/resources/test_files/runtime/Operational/Comparisons/GeneralComparisonEmptySequence.iq
src/test/java/iq/RuntimeTests.java

Bug detected with testing suite. Fixed by changing how unorderedItemSequenceStringsAreEqual is called in RuntimeTests.java
This enabled us to detect further bugs that were previously going unnoticed. All are fixed not and existing test cases are not checked properly.

Testing bug

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/ComparisonOperationIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/MultiplicativeOperationIterator.java

Fix enum warnings.

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java

Reverts Sparksoniq/sparksoniq#162

Revert "Extend HybridIterator in ReturnClause"

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java

Reverts Sparksoniq/sparksoniq#166

Revert "Extend HybridIterator in ReturnClause (Merge Fix)"

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java

Hybrid return clause merge fix

---

src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/RuntimeTupleIterator.java
src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParallelizeFunctionIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParseJsonFunctionIterator.java

Will be reviewed once local where clause is merged

Get rdd with context

---

src/main/java/sparksoniq/jsoniq/item/Item.java
src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
src/main/java/sparksoniq/spark/closures/OrderByClauseSortClosure.java
src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal1.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal10.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal11.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal12.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal13.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal14.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal15.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal16.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal2.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal3.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal4.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal5.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal6.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal7.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal8.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal9.iq
src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocalError1.iq

Local evaluation for orderby clause is implemented. 
Handling empty ordering fields with greatest/least keywords are now fully supported.

Orderby clause local

---

pom.xml

There is a security issue with Spark <= 2.3.2. Upgrading pom.xml to Spark 2.4.

Suppressing security issue message

---

src/main/java/sparksoniq/JsoniqQueryExecutor.java
src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
src/main/java/sparksoniq/spark/SparkSessionManager.java
src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
src/main/resources/test_files/runtime/JsoniqVersion.iq
src/test/java/iq/RuntimeTests.java
src/test/java/iq/SparkRuntimeTests.java
src/test/java/iq/base/AnnotationsTestsBase.java

This PR is only meant to see the diff between the master and the DataFrames development branch. Please do not merge.
The goal is to keep the diff to a minimum and merge back to the master any change orthogonal to this semester project.

DataFrames in FLWOR expressions

---

src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java

Remove unreached getNewRDDFromExpression code block in for and let clauses.
Earlier issue found here:
https://github.com/Sparksoniq/sparksoniq/issues/176

Local clause cleanup

---

src/main/java/sparksoniq/spark/closures/LetClauseMapClosure.java
src/main/java/sparksoniq/spark/closures/OLD_LetClauseMapClosure.java
src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
src/main/resources/test_files/runtime-spark/DataFrames/LetClause1.iq
src/main/resources/test_files/runtime-spark/DataFrames/LetClause2.iq

Dataframes with LetClause implemented. 
Test cases added.

Implement let clause with dataframes.

---

src/main/java/sparksoniq/JsoniqQueryExecutor.java
src/main/java/sparksoniq/spark/closures/OLD_WhereClauseClosure.java
src/main/java/sparksoniq/spark/closures/WhereClauseMapClosure.java
src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause1.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause2.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause3.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause4.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause5.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause6.iq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause7.iq
src/test/java/iq/RuntimeTests.java

Whereclause implemented.
Branch resides on top of letClause PR. This can be evaluated after it is merged.

Where clause df

---

src/main/java/sparksoniq/JsoniqQueryExecutor.java
src/main/java/sparksoniq/Main.java

This should help :)
Query 1 with the entire dataset takes less than 25 seconds.

Optimized for faster local output.

---

src/main/java/sparksoniq/spark/DataFrameUtils.java
src/main/java/sparksoniq/spark/closures/ClosureUtils.java
src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
src/main/java/sparksoniq/spark/closures/LetClauseMapClosure.java
src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
src/main/java/sparksoniq/spark/closures/WhereClauseMapClosure.java
src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
src/main/java/sparksoniq/spark/udf/ForClauseUDF.java

ClosureUtils refactored to DataFrameUtils, now containing functions helping both closures and UDFs.
For clause is implemented with SparkSQL

For clause sql

---

src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
src/main/java/sparksoniq/spark/udf/LetClauseUDF.java

Let clause sql

---

src/main/java/sparksoniq/spark/DataFrameUtils.java
src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java

Where clause sql

---

pom.xml

Getting rid of all warnings upon compiling.

Fix warnings in maven.

---

src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
src/main/resources/test_files/runtime-spark/LocalClauses/CountClauseLocal3.iq

Fix local execution of count clause

---

src/main/java/sparksoniq/JsoniqQueryExecutor.java

Write to stdout if output path is missing.

---

src/main/java/sparksoniq/io/shell/JiqsJLineShell.java

Adjust handling of errors nested in Spark.

---

src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java

Dear Can,
This is the caching for group by. Does it make a difference in the measurements?

Cache intermediate DF in group by

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/ExistsFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DeepEqualFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/EndsWithFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StartsWithFunctionIterator.java
src/main/java/sparksoniq/spark/DataFrameUtils.java
src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
src/main/java/sparksoniq/spark/udf/CountClauseSerializeUDF.java
src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
src/main/java/sparksoniq/spark/udf/GroupClauseSerializeAggregateResultsUDF.java
src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java

Depends on the Kryo instance optimization branch.
Using regular Kryo Outputs gives a performance improvement, as documented by Kryo.

Non buffered output

---

pom.xml
src/main/java/sparksoniq/Main.java
src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
src/main/java/sparksoniq/spark/closures/LetClauseMapClosure.java
src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
src/main/java/sparksoniq/spark/closures/WhereClauseMapClosure.java
src/main/java/sparksoniq/spark/udf/CountClauseSerializeUDF.java
src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
src/main/java/sparksoniq/spark/udf/GroupClauseCreateColumnsUDF.java
src/main/java/sparksoniq/spark/udf/GroupClauseDetermineTypeUDF.java
src/main/java/sparksoniq/spark/udf/GroupClauseSerializeAggregateResultsUDF.java
src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java

A lot of the time was spent on Kryo references. This PR deactivates them, improving performance.

Upgrade Kryo and deactivate references.

---

src/main/java/sparksoniq/Main.java

When an unexpected error happened, nothing was shown on the CLI. This was making debugging less easy.

More informative output in case of general error.

---

src/main/java/sparksoniq/jsoniq/item/ArrayItem.java
src/main/resources/test_files/runtime/Array2.iq

Fix array serialization issue.

---

.gitignore
docs/Error codes.md
docs/Function library.md
src/main/java/sparksoniq/exceptions/AbsentPartOfDynamicContextException.java
src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/context/LastFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/context/PositionFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/resources/test_files/runtime-spark/PositionPredicate1.jq
src/main/resources/test_files/runtime-spark/PositionPredicate2.jq
src/main/resources/test_files/runtime-spark/PositionPredicate3.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate5.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate6.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate7.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate8.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicateError1.jq
src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicateError2.jq

Support for position() and last() in predicates.
https://github.com/RumbleDB/rumble/issues/120
This also works with RDDs (with zipWithIndex for position() and a count action for last()).

Position and Last (local and RDD)

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
src/main/resources/test_files/runtime-spark/PositionPredicate4.jq
src/main/resources/test_files/runtime-spark/PositionPredicate5.jq

Fixes
https://github.com/RumbleDB/rumble/issues/193

Allow numbers in predicates also on Spark.

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/LocalRuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/UserDefinedFunctionCallIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayUnboxingIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParallelizeFunctionIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParquetFileFunctionIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParseJsonFunctionIterator.java
src/main/java/sparksoniq/spark/iterator/function/ParseTextFunctionIterator.java

- getDataFrame(...) return type fixed.
- getRDDAux(...) method defined on Hybrid RI

getDataFrame support for Hybrid RI

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ContextExpressionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java

Current base is tupleRDD branch

Support initial let clause RDDs and DFs without instant materialization

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosure.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause9.jq
src/main/resources/test_files/runtime-spark/PositionPredicate6.jq

Fix bug with empty sequence in predicates or where clauses.

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TypePromotionIterator.java

@AndreaRinaldi1 could this have been an overlook? Thanks!

Suggest bugfix.

---

src/main/java/sparksoniq/spark/DataFrameUtils.java
src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause11.jq
src/main/resources/test_files/runtime-spark/DataFrames/WhereClause8.jq

Fixes https://github.com/RumbleDB/rumble/issues/244

Fix contexts for passing outer variables.

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/control/IfRuntimeIterator.java
src/main/resources/test_files/runtime/ControlIterators/IfExpr12.jq
src/main/resources/test_files/runtime/ControlIterators/IfExpr13.jq
src/main/resources/test_files/runtime/ControlIterators/IfExpr14.jq

Solves #421 
The if expression iterator was incorrectly materializing the data. Now it is implemented in a streaming fashion that also treats empty sequences correctly.

Empty sequence if

---

src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
src/main/java/org/rumbledb/cli/Main.java
src/main/java/sparksoniq/jsoniq/item/ItemComparatorForSequences.java
src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
src/main/java/sparksoniq/semantics/DynamicContext.java
src/main/java/sparksoniq/spark/SparkSessionManager.java
src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
src/test/java/iq/RuntimeTests.java

To reduce the complexity, this is a cherry pick with obvious changes from the other branch.

Cherry pick.

---

src/main/java/sparksoniq/semantics/StaticContext.java

- Introduce InScopeVariable to static Context
- Cleanup Cosmetics of RuntimeIteratorVisitor
- Fix buggy _isRDD usage of HybridRuntimeIterator

7-Improve static context

---

src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectAccumulateFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectIntersectFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectProjectFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectRemoveKeysFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/AvgFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/MaxFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/MinFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/SumFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/ReverseFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DeepEqualFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StringJoinFunctionIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ArrayRuntimeIterator.java

Based on #435 
Implement materialize method in the RuntimeIterator. This replaces getItemsFromIteratorWithCurrentContext method.

11-Materialize function

---

src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java

11-2-Cleanup static context visitor

---

src/main/java/sparksoniq/jsoniq/compiler/translator/expr/CommaExpression.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/ExpressionOrClause.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworExpression.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/postfix/PostFixExpression.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/primary/FunctionDeclaration.java
src/main/java/sparksoniq/jsoniq/compiler/translator/expr/primary/ParenthesizedExpression.java
src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
src/main/java/sparksoniq/semantics/visitor/VisitorHelpers.java
src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic12.jq
src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic13.jq
src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic9.jq

Support execution modes for Static User Defined Functions

---

src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-KMeans1.jq
src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-LogisticRegression1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Binarizer1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Tokenizer1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-VectorAssembler1.jq

Load data through json-file and apply annotate() in existing ml tests

Use annotate()ted item data (rdd or local)  in existing ml tests

---

src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-KMeans1.jq
src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-LogisticRegression1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Binarizer1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Tokenizer1.jq
src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-VectorAssembler1.jq

Estimators, transformers and parameters in the catalog are now alphabetically sorted.
This is technically just a cosmetic change, but I believe that there is a good chance that the previous catalog had some incorrect parameters. I believe most of these are now fixed.

Update ml catalog with sorted and improved ml catalog

---

src/main/java/org/rumbledb/runtime/functions/sequences/value/DeepEqualFunctionIterator.java
src/main/java/org/rumbledb/runtime/functions/sequences/value/SameElementsAndLengthClosure.java
src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual10.jq
src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual11.jq
src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual2.jq

After trying a few approaches, this is the best I've been able to come up with given the limitations imposed by comparing an RDD with a local iterator and comparing two RDDs with different numbers of partitions.

Parallelized deep-equal function

---

src/main/java/org/rumbledb/compiler/VisitorHelpers.java
src/main/java/org/rumbledb/runtime/functions/base/Functions.java

Only cosmetic changes to functions.java
When I look at the BuiltinFunctions Catalog, we have bunch of static final class objects. It looks like defining an Enum type for these would be fitting and it would simplify the code. I was thinking of creating an issue for this to address it later. Do you have any reservations against this idea @ghislainfourny?

Cosmetic improvements to Functions.java

---

src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java

Prevent redundant vectorization

---

src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java
src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java
src/main/java/sparksoniq/spark/DataFrameUtils.java
src/main/resources/test_files/runtime-spark/ReturnDataFrame1.jq
src/main/resources/test_files/runtime-spark/ReturnDataFrame2.jq
src/main/resources/test_files/runtime-spark/ReturnRDD1.jq
src/main/resources/test_files/runtime-spark/ReturnRDD2.jq
src/main/resources/test_files/runtime-spark/ReturnRDD3.jq

Fixes #615 
This should help with your demo.
Enjoy!

Fix return clause parallel

---

src/main/java/org/rumbledb/runtime/flwor/FlworDataFrameUtils.java

#652 Made it clear that code here is way too obfuscated. I tried to refactor this and make it cleaner.
Fixes #652

Improve getGroupProjectSQL

---

docs/RumbleML.md

@ghislainfourny Here is a draft for the documentation and the updated RumbleML catalog. I would appreciate any feedback to improve it.

Add RumbleML Documentation

---

src/main/java/org/rumbledb/api/Item.java
src/main/java/org/rumbledb/items/Base64BinaryItem.java
src/main/java/org/rumbledb/items/BooleanItem.java
src/main/java/org/rumbledb/items/DateItem.java
src/main/java/org/rumbledb/items/DateTimeItem.java
src/main/java/org/rumbledb/items/DayTimeDurationItem.java
src/main/java/org/rumbledb/items/DecimalItem.java
src/main/java/org/rumbledb/items/DoubleItem.java
src/main/java/org/rumbledb/items/DurationItem.java
src/main/java/org/rumbledb/items/HexBinaryItem.java
src/main/java/org/rumbledb/items/IntItem.java
src/main/java/org/rumbledb/items/IntegerItem.java
src/main/java/org/rumbledb/items/ItemComparator.java
src/main/java/org/rumbledb/items/ItemImpl.java
src/main/java/org/rumbledb/items/NullItem.java
src/main/java/org/rumbledb/items/StringItem.java
src/main/java/org/rumbledb/items/TimeItem.java
src/main/java/org/rumbledb/items/YearMonthDurationItem.java
src/main/java/org/rumbledb/runtime/operational/ComparisonOperationIterator.java
src/test/resources/test_files/runtime/Operational/Comparisons/ValueComparisonBinaries.jq
src/test/resources/test_files/runtime/Operational/Comparisons/ValueComparisonDurations.jq

New comparison

---

src/main/java/org/rumbledb/compiler/TranslationVisitor.java
src/main/java/org/rumbledb/parser/Jsoniq.g4
src/main/java/org/rumbledb/parser/JsoniqParser.java
src/test/resources/test_files/runtime/InlineFunction1.jq

Allow for empty body.

---

docs/Error codes.md
src/main/java/org/rumbledb/errorcodes/ErrorCode.java
src/main/java/org/rumbledb/exceptions/NoTypedValueException.java
src/main/java/org/rumbledb/runtime/flwor/clauses/OrderByClauseSparkIterator.java
src/test/resources/test_files/runtime/OrderBy1.jq
src/test/resources/test_files/runtime/OrderByError1.jq

Order by key

---

src/main/java/org/rumbledb/runtime/control/SwitchRuntimeIterator.java
src/test/resources/test_files/runtime/ControlIterators/SwitchExpression5.jq

Fix bug in switch expressions.

---

src/main/java/org/rumbledb/api/Rumble.java
src/main/java/org/rumbledb/api/SequenceOfItems.java
src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
src/main/java/org/rumbledb/compiler/ExpressionClassificationVisitor.java
src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
src/main/java/org/rumbledb/config/RumbleRuntimeConfiguration.java
src/main/java/org/rumbledb/runtime/scripting/ProgramIterator.java
src/main/java/org/rumbledb/runtime/scripting/block/StatementsWithExprIterator.java
src/main/java/org/rumbledb/runtime/typing/TreatIterator.java
src/test/java/iq/DeltaUpdateRuntimeTests.java
src/test/java/iq/RuntimeTests.java
src/test/java/iq/RuntimeTestsNoInlining.java
src/test/java/iq/UpdatesForRumbleBenchmark.java

These changes make the scripting compatible with updates, including deltalake updates, and include a CLI argument to toggle applying updates.

Deltalake scripting updates

---

src/main/java/org/rumbledb/api/Rumble.java
src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
src/main/java/org/rumbledb/compiler/ExpressionClassificationVisitor.java
src/test/java/iq/RuntimeTests.java

Run spotless for the deltalake changes

Delta Lake/Scripting changes: run mvn spotless

---

.github/workflows/maven.yml

Fix CI/CD to run tests in parralel

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Fix the typo with the label
