RumbleDB/rumble

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/arrays/ArraySizeFunctionIterator.java
- src/main/resources/test_files/runtime/FunctionArray/FunctionArraySize.iq
Lazy evaluation and empty sequence support added to array size iterator
PS: I'm purposefully adding the test cases such as ( (), () ) . It's semantically equivalent to an empty sequence however, it prevents the antipattern of checking for emptySequenceIterator. This test case enforces that we're checking the hasNext to be false rather than simply checking if iterator is an empty sequence iterator. If latter is done (()) would be handled successfully however since ( (), (), ) is a commaExpression at the higher level, emptySequence check would've failed.
> Array size itr

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/arrays/ArrayDescendantFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectDescendantFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectDescendantPairsFunctionIterator.java
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant5.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant4.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant5
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant5.iq
Lazy evaluation implemented for descendant functions. Lazy evaluation is implemented in a different manner due to the added complexity caused by recursive structure of the function calls. Each item in the original sequence is recursively investigated to find descendant items of the desired type which are then stored in a queue. Once results returned from the first item is exhausted through next calls, the following item is recursively investigated in the same manner and its results are stored in the queue and so on. 
Empty sequence test cases are activated following the bugfix applied in the previous PR:  https://github.com/Sparksoniq/sparksoniq/pull/57
> Descendant functions

- src/main/java/sparksoniq/jsoniq/runtime/iterator/EmptySequenceIterator.java
Since hasNext is always false in emptySequenceIterator iterator by definition. I believe throwing an exception rather than returning null would make more sense in the next() call.
> change next() call of EmptySequence Iterator

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/ConcatFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/StringConcatIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ObjectConstructorRuntimeIterator.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
- src/main/resources/test_files/runtime/FunctionString/ConcatFunction2.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError1.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError2.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError3.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError4.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError5.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError6.iq
- src/main/resources/test_files/runtime/FunctionString/ConcatFunctionError7.iq
- src/main/resources/test_files/runtime/Operational/StringConcat1.iq
- src/main/resources/test_files/runtime/Operational/StringConcat2.iq
- src/main/resources/test_files/runtime/Operational/StringConcatError1.iq
- src/main/resources/test_files/runtime/Operational/StringConcatError2.iq
- src/main/resources/test_files/runtime/Operational/StringConcatError3.iq
- src/main/resources/test_files/runtime/PrimaryIterators/ObjectConstructor1.iq
- src/main/resources/test_files/runtime/PrimaryIterators/ObjectConstructor2.iq
Issue solved: https://github.com/Sparksoniq/sparksoniq/issues/83
String concatenation functions have been improved to work with not only strings but all atomic types.
Test cases changed accordingly
Edit: Also fixed issue: https://github.com/Sparksoniq/sparksoniq/issues/84
Type casting bug fixed with RuntimeIteratorVisitor.
Object constructor improved to work with multiple objects returning from the same iterator.
Test case added.
> Object constructor

- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant1.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant2.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant3.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant4.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayDescendant5.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten1.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten2.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten3.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayFlatten4.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers1.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers2.iq
- src/main/resources/test_files/runtime/FunctionArray/FunctionArrayMembers3.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant1.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant2.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant3.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant4.iq
- src/main/resources/test_files/runtime/FunctionObject/FunctionObjectDescendant5.iq
Cleanup PR.
Unnecessary let statements have been cleared from most of the test cases.
> Remove unnecessary FLWOR clauses from tests

- src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
- src/main/resources/test_files/runtime/ObjectUnquotedKey1.iq
- src/main/resources/test_files/runtime/ObjectUnquotedKey2.iq
Issue fixed: https://github.com/Sparksoniq/sparksoniq/issues/62
Support for unquoted object keys implemented. Test cases added
> Implement unquoted object keys

- src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
- src/main/java/sparksoniq/semantics/DynamicContext.java
- src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/base/FlowrClauseSparkIterator.java
- src/main/resources/test_files/runtime-spark/EmptySequence.iq
- src/main/resources/test_files/runtime-spark/LocalClauses/LocalLet1.iq
- src/main/resources/test_files/runtime-spark/LocalClauses/LocalLet2.iq
- src/main/resources/test_files/runtime-spark/LocalClauses/LocalLet3.iq
- src/main/resources/test_files/runtime-spark/LocalClauses/LocalLet4.iq
- src/main/resources/test_files/runtime-spark/LocalClauses/LocalLet5.iq
I have partially implemented the local let clause support. The following query can be evaluated fully locally.
let $o := {"foobar": 2}
return $o
However, I have ran into an issue that's currently blocking me. Running the following query
let $o := {"foobar": 2}
let $a := ("foo" || "bar")
return $o.$a
causes the following: [ERROR] Error [err: XPDY0130 ] Runtime error retrieving variable $o value
I was wondering whether this was caused by an issue in context chaining or not passing the assignment from the "first let"s tuple(s*) into the "second let". 
Additionally, while looking into the issue of possibly faulty context chaining, I found the "chaining first and opening the child later" much more sensible and made such changes in my last commit. I'd appreciate the feedback on both this change …
> Local let clause implementation

- src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
This improves the serialize function. There was a bug in case a value appears multiple times, and a string builder is more performant.
> Fix serialize function.

- src/main/java/sparksoniq/JsoniqQueryExecutor.java
- src/main/java/sparksoniq/spark/SparkSessionManager.java
- src/main/resources/test_files/runtime/JsoniqVersion.iq
- src/test/java/iq/RuntimeTests.java
- src/test/java/iq/SparkRuntimeTests.java
- src/test/java/iq/base/AnnotationsTestsBase.java
While trying to fix a bug with dataframe testing, I have re-organized the code and comments in testing and jsoniq queryExecutor. I believe these changes can be applied to master. 
The only two functional changes are the following:
1-) Spark configuration of the testing suite has been updated to match the current/common parameters (In RuntimeTests.java line 74)
2-) Parse function used in testing have been made identical to the visitor call in JsoniqQueryExecutor. (In AnnotationTestBase.java line 181). 
The second change resulted in me updating the test JsoniqVersion.iq. Previously, this test has been regarded as ShoulNotParse. However sparksoniq seems to be able to parse it and produce the output "2", which is identical behavior to Zorba. Is this behavior correct/is there something that …
> Improve code organization and styling for testing

- src/main/java/sparksoniq/JsoniqQueryExecutor.java
In the interactive shell as well as in local output, the serialization should put one item per line, with no parentheses or commas around -- this was already the case when writing back to HDFS.
(For tests, the behavior is unchanged as this is internal and it can wait until the test refactoring).
In particular, as a consequence of this fix and the other two fixing PRs, now, outputs can be re-read as inputs.
> Fixing serialized output to follow standard practice

- src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/MultiplicativeOperationIterator.java
- src/main/resources/test_files/runtime/Operational/MultiplicativeOp4.iq
idiv must always return an integer. Fixes https://github.com/Sparksoniq/sparksoniq/issues/74
https://www.w3.org/TR/xpath-functions-31/#func-numeric-integer-divide
> Fix idiv result.

- src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
Reusing Dynamic context optimization was not actually used in the groupby clause. This fixes the bug
> Fix dynamic context usage in groupby

- src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
This PR is based on #249.
Error message handling for exceptions thrown within spark execution is improved. Previously custom exception's and their messages were not displayed to the user and spark implementation details were exposed as such:
Edit: The exception's root cause is fetched to give the most precise and relevant detail
[ERROR] Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2.0 (TID 3, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$259: (array<binary>) => array<string>)
With this PR this turns into:
[ERROR] Error [err: XPDY0130 ] Order by expressions must return singleton atomics for each row
> Spark exception message

- docs/Getting started.md
- docs/Run on a cluster.md
- docs/install.md
- pom.xml
- src/main/java/sparksoniq/io/json/JiqsItemParser.java
The only material fix (besides upgrading version to 0.9.7) is to no longer use JSONObject.keySet(), because some Spark environments have old versions of org.json. This fix makes us backward compatible with all environments.
> Fix keySet issue with older org.json.

- src/main/java/sparksoniq/JsoniqQueryExecutor.java
- src/main/java/sparksoniq/Main.java
- src/main/java/sparksoniq/ShellStart.java
- src/main/java/sparksoniq/config/SparksoniqRuntimeConfiguration.java
- src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
- src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
- src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
- Deprecate ShellStart class, replacing with --shell yes CLI parameter on the Main class.
- Add usage and examples when no parameters are used, made sure usage also appears when using java without spark-submit.
- Clean up and unify use of the CLI parameters into the SparksoniqRuntimeConfiguration class
- ShellStart still works and redirect to Main
> Clean up CLI.

- src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
For ordering queries, the same DF was computed three times. This activates caching.
> Cache intermediate view.

- src/main/java/sparksoniq/JsoniqQueryExecutor.java
- src/main/java/sparksoniq/config/SparksoniqRuntimeConfiguration.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/primary/VariableReference.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ContextExpressionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/RuntimeTupleIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
Adding a function to the runtime iterator APIs to get the list of variables that any expression or clauses depends on via the dynamic context. Based on this, we will be able, in the new DataFrames implementation, to only pass those variables that are actually needed to UDFs, and to project away columns that are not needed by subsequent clauses.
> Variable dependencies

- src/main/java/sparksoniq/exceptions/TreatException.java
- src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
- src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
- src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/TreatExpression.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
- src/main/java/sparksoniq/semantics/types/ItemTypes.java
- src/main/java/sparksoniq/semantics/types/SequenceType.java
- src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
- src/main/resources/test_files/runtime/Treat.jq
- src/main/resources/test_files/runtime/TreatError1.jq
- src/main/resources/test_files/runtime/TreatError2.jq
- src/main/resources/test_files/runtime/TreatError3.jq
- src/main/resources/test_files/runtime/TreatError4.jq
- src/main/resources/test_files/runtime/TreatError5.jq
- src/main/resources/test_files/runtime/TreatError6.jq
- src/main/resources/test_files/runtime/TreatError7.jq
- src/main/resources/test_files/runtime/TreatError8.jq
- src/main/resources/test_files/runtime/TreatError9.jq
This branch includes the implementation for the **treat as** operator (iterator and expression).
From the W3C documentation:
>  
The semantics of expr1 treat as type1 are as follows:
- During static analysis:
The static type of the treat expression is type1. This enables the expression to be used as an argument of a function that requires a parameter of type1.
- During expression evaluation:
If expr1 matches type1, using the rules for SequenceType matching, the treat expression returns the value of expr1; otherwise, it raises a dynamic error [err:XPDY0050]. 
If the value of expr1 is returned, its identity is preserved. The treat expression ensures that the value of its expression operand conforms to the expected type at run-time.
> Treat as operator

- src/main/java/sparksoniq/exceptions/CastableException.java
- src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
- src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
- src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
- src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
- src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
- src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSingleType.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/CastableExpression.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
- src/main/java/sparksoniq/jsoniq/item/AtomicItem.java
- src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
- src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
- src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
- src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
- src/main/java/sparksoniq/jsoniq/item/NullItem.java
- src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
- src/main/java/sparksoniq/jsoniq/item/StringItem.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastableIterator.java
- src/main/java/sparksoniq/semantics/types/AtomicType.java
- src/main/java/sparksoniq/semantics/types/AtomicTypes.java
- src/main/java/sparksoniq/semantics/types/SingleType.java
- src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
- src/main/resources/test_files/runtime/Castable.jq
- src/main/resources/test_files/runtime/CastableError1.jq
- src/main/resources/test_files/runtime/CastableError2.jq
- src/main/resources/test_files/runtime/CastableError3.jq
This branch includes the implementation of the **castable as** operator (iterator and expression).
From the W3C documentation:
> The expression E castable as T returns true if the result of evaluating E can be successfully cast into the target type T by using a cast expression; otherwise it returns false. If evaluation of E fails with a dynamic error, the castable expression as a whole fails.
To keep the naming of types consistent with what W3C is using, I introduced _simpleType_ and _singleType_ in Jsoniq.g4, together with the new Classes _AtomicType_, _FlworVarSingleType_ and the enum _AtomicTypes_. 
I forgot to add _NullItem_ to _AtomicTypes_ Enum, but I will do in the next version of the pr.
There is just one small naming inconsistency, that is _FlworVarSingleType_ has a …
> Castable as operator

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/SubstringBeforeFunctionIterator.java
- src/main/resources/test_files/runtime/FunctionString/SubstringBefore.jq
This branch introduces the **substring-before** builtin function (with two string arguments) as described in the [W3C documentation](https://www.w3.org/TR/xpath-functions-30/#func-substring-before).
> Substring before

- .travis.yml
I was considering adding caching for maven imports in order to improve the speed of our travis builds. Do you see any potential problems with this addition @wscsprint3r ?
> Add caching to travis build

- src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
- src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
- src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
fcn_name typo fixed to fn_name
snake_case is now used for variables defined in the grammar. This helps differentiating from parser rules defined in camelCase and lexer rules defined in CapitalCamelCase
No functional changes.
> Standardize variables in .g4, fix 'fcnName' typo

- src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayUnboxingIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
This PR simplifies the openLocal() method of HybridRuntimeIterators by removing the context parameter while providing the same functionality.
It seems to me that the openLocal() method is only used after the open() method is called on the hybrid iterator. This operation always sets the _currentDynamicContext to the given dynamic context on open(DynamicContext context) call. Hence, passing the same parameter again to openLocal seems redundant as this is already accessible in the member field _currentDynamicContext. Furthermore, this caused various redundant assignments in openLocal() method implementations. These are now cleaned up.
> HybridRuntimeIterator - openLocal() simplified

- src/main/java/sparksoniq/exceptions/InvalidTimezoneException.java
- src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustDateTimeToTimezone.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustDateToTimezone.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustTimeToTimezone.java
- src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezone.jq
- src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezoneError1.jq
- src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezoneError2.jq
In this branch I include the builtin functions to adjust dateTimes, dates and times according to a specified (or not specified) timezone, as described thoroughly in [W3C specs](https://www.w3.org/TR/xpath-functions-30/#timezone.functions). 
_Spoiler:_ there are quite some rules to determine the result based on the different parameters.
> Adjust time zone

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
- Use checks for function existence rather than exceptions
- Extract RuntimeIterator generation for built-in functions to getBuiltInFunctionIterator()in the Functions Catalog
> Refactor function catalog

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/StaticUserDefinedFunctionCallIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
I tried to improve the naming of classes for the PR #377 . Please feel free to address anything that doesn't suit you as it's mostly a matter of preference in the road to clarity.
The issues I tried to address mainly were
- The duality of DynamicallyResolvedFunctionCallIterator and DynamicFunctionCallIterator as I assumed the difference would not be immediately clear in my opinion for a new pair of eyes. These are now renamed to StaticUserDefinedFunctionCallIterator and DynamicUserDefinedFunctionCallIterator respectively.
- The ambiguity of functionItemCalliterator and the name of the iterator  field of this class . I believe naming these UserDefinedFunctionCallIterator and functionBodyIterator makes the intention of the class much more clearer. 
There could be a new issue with the new …
> Improve naming for User defined function call classes

- src/main/java/sparksoniq/spark/DataFrameUtils.java
- src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause11.jq
The current implementation was incorrectly assuming that all equivalent keys within a group would be exactly the same.
When this is not the case, one of the values should be arbitrarily picked.
Replacing in Spark SQL
array_distinct(...)
with array(first(...))
This problem is already present in the master with, for example, integers and decimals (see added test).
> Make sure that only one grouping key is taken when keys in the same group are different.

- src/main/java/sparksoniq/JsoniqQueryExecutor.java
- src/main/java/sparksoniq/Main.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
- src/main/java/sparksoniq/semantics/DynamicContext.java
- src/main/java/sparksoniq/spark/SparkSessionManager.java
- src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
- src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
- src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
RDD and DF support added to FLWOR tuples with individual maps.
DF -> RDD -> Local fallback implemented (IteratorMetadata used for DF -> Fallback)
Both data structures have their own get and put methods. These methods also benefit from iteratormetadata for better error messages.
Collecting an RDD is extracted to a method in SparkContextManager.
Logging messages extracted to a method in the Main class.
> Add RDD support to FLWOR tuple

- pom.xml
Since #387 was merged into master, when running Rumble, I get the following. 
> Failed to load org.rumbledb.Main
java.lang.ClassNotFoundException: org.rumbledb.Main
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
at …
> Edit MainClass path

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
- src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic-Error4.jq
The current master is throwing a NullPointerException if a non-existing function is called. For example, when evaluating `nonExistingFunction("hello")`, the following is the stacktrace of the exception. 
> java.lang.NullPointerException
at sparksoniq.jsoniq.runtime.iterator.functions.FunctionItemCallIterator.initIsRDD(FunctionItemCallIterator.java:212)
at sparksoniq.jsoniq.runtime.iterator.HybridRuntimeIterator.isRDD(HybridRuntimeIterator.java:56)
at sparksoniq.jsoniq.runtime.iterator.functions.StaticUserDefinedFunctionCallIterator.initIsRDD(StaticUserDefinedFunctionCallIterator.java:126)
at sparksoniq.jsoniq.runtime.iterator.HybridRuntimeIterator.isRDD(HybridRuntimeIterator.java:56)
...
> Throw UnknownFunctionCallException if non-existing function is called

- src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TypePromotionIterator.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosure.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
- src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
- src/main/resources/test_files/runtime-spark/DataFrames/WhereClause10.jq
- src/main/resources/test_files/runtime-spark/PositionPredicate7.jq
- src/main/resources/test_files/runtime-spark/PositionPredicate8.jq
The EBV was not considered, although where clauses and predicates should.
https://www.w3.org/TR/xquery-30/#id-ebv
For predicates, there is the special case where the sequence is a single numeric item. Then the EBV is not taken, but the position is checked instead.
https://www.w3.org/TR/xquery-30/#id-filter-expression
> Use EBV in where clauses and predicates when pushing down to DF.

- src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
- src/main/resources/test_files/runtime-spark/Pushdown/KeysDF3.jq
- src/main/resources/test_files/runtime-spark/Pushdown/KeysRDD3.jq
Based on #393. This PR introduces a tiny change that fixes the crashes caused by empty dataframe being passed as input to order by clause. This would result in an empty sql statement which causes the crash.
Tests added.
@ghislainfourny Should the short circuit mentioned above (seen in OrderByClauseSparkIterator.java file) be added to other FLWOR clauses as well? It could save a bit of unnecessary computation and querying when operating on empty sequences. However this introduces an additional count() action which might be costly.
> Fix order clause empty df handling

- src/main/java/sparksoniq/spark/DataFrameUtils.java
- src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
- src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
- src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause12.jq
@CanBerker this is a bug found in class. It would be nice if we can review/merge today and I will do an interim release also with the bugs solved last week. Thanks!
This partially solves https://github.com/RumbleDB/rumble/issues/410 for the let clause (and potentially group clauses, untested). Other clauses can be fixed later, with all needed tests.
Also, this opens the way to the treatment of FLWOR dataframes with other types than binaries in UDFs. I am afraid we have no choice but to pass an array for each type to the UDFs (and will need to extend this to all types), except if we discover that Spark SQL supports polymorphic UDFs in some way...
> Fix count optimization with let group

- src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
- src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpressionError2.jq
This is based on #440 
Original implementation did not perform static checks on the condition and default case of the typeswitch expression. I have added these in this PR.
> 12-2-Add static type checking for typeswitch default case

- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/ExpressionOrClause.java
- src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/OrderByClauseExpr.java
Depends on #441 
This PR adds missing getDescendants implementation for OrderByClauseExpression
> 13-2-Fix order by clause expr

- src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchCase.java
- src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchRuntimeIterator.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
Original typeSwitchExpression implementation created variableReferenceIterators only to access their names. I have eliminated the iterator generation and passed the names in directly instead. This not only improves performance by eliminating redundant object creation, but also improves correctness. The use of variableReference in the case of $a in the example below is to simply define the variable, not look it up from current (static or dynamic) context. VariableReferenceIterator should be used **only** for the return clauses of 2nd and 3rd cases where an actual variable referencing should be performed. 
typeswitch(4.234243e3)
case $a as hexBinary+ return "not this"
case $b as boolean | double? | base64Binary? return ($b cast as string) || " correct"
case $c as string | decimal? return $c …
> Simplify typeSwitchExpression by removing redundant variableReferenceIterators

- src/main/java/sparksoniq/jsoniq/tuple/FlworKeyComparator.java
- src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
- src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/expression/OrderByClauseAnnotatedChildIterator.java
- src/main/java/sparksoniq/spark/iterator/flowr/expression/OrderByClauseExprWithIterator.java
- src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
- src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
- src/test/java/iq/FrontendTests.java
This one may be a matter of taste but I tried to improve the naming of orderbyClauseSparkIteratorExpression as it did not mean much to me in its original state. This PR does not aim to change the functionality. It merely renames and extracts a runtimeIterator to a variable in 2 UDFs
Basically this class consists of an orderByClause's subExpression (called orderByClauseExpr), and the iterator generated from the said expression. 
As a general remark, especially in the past few months, I have found that the 'expression' keyword to be used ambiguous ways in multiple contexts. While the meaning becomes clear once you are familiar with the context, for future maintainability of the project and onboarding of new developers, it may be very helpful to disentangle such meanings with hopefully …
> Improve naming of orderbyClauseSparkIteratorExpression and its usage

- src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
- src/main/java/sparksoniq/spark/ml/GetTransformerFunctionIterator.java
- src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
- src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
Based on #415. 
Apply transformer now takes the transformer to be applied directly as a parameter rather than generating it. This will allow us to use the same class for applying the transformers that result from fitting an estimator.
> Refactor applyTransformerIterator to take a Transformer as parameter

- src/main/java/org/rumbledb/items/parsing/ItemParser.java
- src/main/resources/test_files/runtime-spark/RumbleML/MLEstimatorKMeans1.jq
As we have discussed in the meeting I have initially implemented SparseVector to ObjectItem mapping.
As per our discussion, I have investigated whether dense and sparse vectors can co-exist within the same dataframe. And this is permitted not only across different columns, but within the same column as well (this can be observed [here](https://spark.apache.org/docs/latest/ml-features.html#pca). 
For this reason, I have extended the implementation to map sparseVectors to objectItems and denseVectors to arrayItems. Do you see any problems with this approach?
> Improve vectorUDT to rumbleItem mapping

- src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
- src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
- src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
- src/main/java/sparksoniq/spark/ml/GetEstimatorFunctionIterator.java
- src/main/java/sparksoniq/spark/ml/GetTransformerFunctionIterator.java
Extracted some operations to functions for increased readability. These are mostly cosmetic changes.
Functional change 1: Error messages referring to partially applied functions. Previously name of a function was not specified when a validation error with arguments of a partially applied function occurred. Now the partially applied function will be referred as "partially applied x" function with x being the original function that was partially applied.
Functional change 2: Introduced UUIDs to internal estimator and transformer variable parameter names. This will prevent collisions with user variables.
> Tidyup apply estimator, apply transformer, FunctionItemCallIterator

- src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
- src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
This is mostly cosmetic. Estimator/transformer validations extracted to a method to reduce code duplication. There are also small renames.
> Cleanup ml catalog's getter/validator methods

- docs/Error codes.md
- src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
- src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
- src/main/java/org/rumbledb/exceptions/MLInvalidDataFrameSchemaException.java
- src/main/java/org/rumbledb/exceptions/MLNotADataFrameException.java
- src/main/java/org/rumbledb/expressions/operational/TreatExpression.java
- src/main/java/org/rumbledb/items/parsing/ItemParser.java
- src/main/java/org/rumbledb/runtime/functions/base/Functions.java
- src/main/java/sparksoniq/semantics/types/ItemType.java
- src/main/java/sparksoniq/spark/DataFrameUtils.java
- src/main/java/sparksoniq/spark/ml/AnnotateFunctionIterator.java
- src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
- src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes2.jq.disabled
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError2.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError3.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError4.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-Transformer1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Estimator-Error1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Transformer-Error1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Transformer1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD1.jq
- src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Multiple1.jq.disabled
~@ghislainfourny I have recently been working on item to native java type conversions. We need this to outsource the computation to the SparkML framework, as it would not be able to operate on rumble items. The conversion of common atomic items is already in place. I was hoping I could get your feedback in this week's meeting before moving on to the complex types.~
Edit: annotate(object*, object) as object* is designed to facilitate passing items to SparkML components.
Given sequence of items are converted to a DataFrame of items using the given schema. This underlying implementation detail needs to be exposed for the time being until full schema support is added to Rumble
> Implement (annotate(object*, object) as object*) function: Local/RDD -> DataFrame conversion with schema

- src/main/java/org/rumbledb/runtime/RuntimeIterator.java
For boolean(), the rules [here](https://www.w3.org/TR/xpath-functions-30/#func-boolean) indicate that types derived from string and anyURI should also be handled. I have implemented this here in preparation for my anyURI implementation by calling `canBePromotedTo`, for which anyURI should return string, if I have interpreted this correctly.
> Bringing up to spec so that boolean() has the expected behaviour

- src/main/java/org/rumbledb/compiler/TranslationVisitor.java
Performance improvement for the translation. This should significantly reduce the size of the expression tree.
> Bypass comma expression

- src/main/java/org/rumbledb/exceptions/MLInvalidDataFrameSchemaException.java
- src/main/java/sparksoniq/spark/DataFrameUtils.java
- src/main/java/sparksoniq/spark/ml/AnnotateFunctionIterator.java
This is mostly cosmetic.  I have tried to improve the annotate() exceptions while also separating the exceptions caused in DataFrameUtils class from annotate method(). This will make it easier to re-use these utility methods without them mentioning annotate() in their exceptions.
> Improve annotate() and DataFrameUtils exceptions

- pom.xml
According maven documentation [here](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Available_Variables) "project.basedir" should be used as alternatives such as "basedir" or "pom.basedir" are now deprecated.
Spotless configuration for file inclusion and exclusion is added as described [here](https://github.com/diffplug/spotless/tree/master/plugin-maven#file-includes-and-excludes). These relative paths are unfortunately not prefixed with a form of "basedir". This is because no form of maven basedir specification worked with these. They do however function properly in the current state with relative paths.
Added spotless error for unused imports.
> Improvements with spotless and basedir usage in pom.xml

- src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
The query given in the example below would never create an execution time log. The reason is the given log paths fits none of the expected patterns which are: 
- "file://"
- "hdfs://"
- "./"
```
noglob spark-submit --master local[*] --conf "spark.driver.host"="127.0.0.1" 
spark-rumble-1.4-jar-with-dependencies.jar --query-path my-query.jq 
--output-path my-output.json --log-path my-log.txt
```
This PR adds an OurBadException so that this does not fail silently for the future. The path given in the example above still needs to be handled. Should I create an issue for this or would you like to take this PR over @ghislainfourny ?
> Prevent silent failing of unhandled log paths

- src/main/java/org/rumbledb/runtime/functions/input/JsonFileFunctionIterator.java
- src/main/java/org/rumbledb/runtime/functions/input/TextFileFunctionIterator.java
- src/main/java/org/rumbledb/runtime/functions/input/UrlValidator.java
@CanBerker this is the first release since the introduction of the URL validator. Unfortunately, it does not work when reading from other file systems than HDFS on Amazon EMR (like S3). I had to fix the code as we need to use FileContext, not FileSystem.
> Fix access to other storage layers than HDFS.

- src/main/java/org/rumbledb/items/FunctionItem.java
- src/main/java/org/rumbledb/shell/ANSIColor.java
- src/main/java/org/rumbledb/shell/RumbleJLineShell.java
@ghislainfourny I had a visually customized Rumble version running during my thesis demo. I wanted to share the colored output customization by removing the other demo-specific bits.
If you think this would be nice feature we can tweak the shell's look to your liking and add this to the master. 
Default look:
Custom look at the moment:
> Implement colored outputs

- src/main/java/org/rumbledb/runtime/HybridRuntimeIterator.java
This does not affect existing code, but is a preparation of more code to be merged for conditional expressions, switch expressions and typeswitch expressions where the RDDness of the branches might differ and we need to lift up to RDD to avoid errors.
> Lift up local iteration to RDD instead of throwing error.

- src/main/resources/test_files/runtime/LibraryModules/modulerepeatedimport.jq
I added a test case which I think should fail currently. I don't know how to run the tests, so I don't know if it actually breaks. I think that this is due to a bug: if I include `moduleA` and `moduleB`, `moduleA` should be allowed to include `moduleB` without me knowing.
> Add test case that shows that importing a module repeatedly is broken.

- docs/CLI.md
- src/main/java/org/rumbledb/compiler/DynamicContextVisitor.java
- src/main/java/org/rumbledb/compiler/TranslationVisitor.java
- src/main/java/org/rumbledb/config/RumbleRuntimeConfiguration.java
- src/main/java/org/rumbledb/context/DynamicContext.java
- src/main/java/org/rumbledb/shell/RumbleJLineShell.java
- src/test/java/iq/base/AnnotationsTestsBase.java
- src/test/resources/test_files/runtime/PostFixObjectLookup/ErrorPostFixObjectLookup4.jq
Example uses:
echo '{ "foo" : [ 100, 200 ] }' | java -jar rumbledb.jar -q '$$.foo[]' --context-item-input -
echo '{ "foo" : [ 100, 200 ] }' | java -jar rumbledb.jar -q '$$.foo[]' -i -
echo '{}}}}[[[}' | java -jar rumbledb.jar -q '$$' --context-item-input - --context-item-input-format text
java -jar rumbledb.jar -q '$$' --context-item 'foo'
java -jar rumbledb.jar -q '$$' -I 'foo'
> Finalizing command line parameters for context item values

- README.md
- pom.xml
- src/main/java/org/rumbledb/compiler/ExecutionModeVisitor.java
- src/main/java/org/rumbledb/compiler/SequentialClassificationVisitor.java
- src/main/java/org/rumbledb/context/GlobalVariables.java
- src/main/java/org/rumbledb/context/InScopeVariable.java
- src/main/java/org/rumbledb/expressions/module/VariableDeclaration.java
- src/main/java/org/rumbledb/expressions/scripting/annotations/Annotation.java
- src/main/java/org/rumbledb/expressions/scripting/declaration/CommaVariableDeclStatement.java
- src/main/java/org/rumbledb/expressions/scripting/declaration/VariableDeclStatement.java
- src/main/java/org/rumbledb/expressions/scripting/loops/FlowrStatement.java
- src/main/java/org/rumbledb/expressions/scripting/loops/ReturnStatementClause.java
- src/main/java/org/rumbledb/expressions/scripting/loops/WhileStatement.java
- src/main/java/org/rumbledb/runtime/functions/StaticUserDefinedFunctionCallIterator.java
- src/main/java/org/rumbledb/runtime/scripting/ProgramIterator.java
- src/main/java/org/rumbledb/runtime/scripting/block/StatementsWithExprIterator.java
- src/main/java/org/rumbledb/runtime/scripting/loops/ExitStatementIterator.java
- src/main/java/org/rumbledb/runtime/typing/TreatIterator.java
- added this. to lots of places to get rid of warnings
- fixed UTF-8 and deprecated args notation in pom.xml
- fixed version of resources and release for stability
> Fix mvn compile warnings

- src/main/java/org/rumbledb/compiler/ProjectionPushdownVisitor.java
- src/main/java/org/rumbledb/runtime/flwor/clauses/OrderByClauseSparkIterator.java
This PR contains some steps towards merging the work of dominik. It includes:
- disable OrderByClauseSparkIterator.createOrderExpression(). many errors happen due to 
OrderByClauseSparkIterator.createOrderExpression() trying to access the resultingtype which is not set. The NativeClauseContext is created in OrderByClauseSparkIterator.tryNativeQuery without a resultingType. I disabled this new functionality and now it just falls back to not using a native query
- In flowr clauses, the last LET clause was often deleted. This happened due to the new ProjectionPushdownVisitor not correctly visiting all let clauses. Now it visits them all
I left in the original codes as references. These two changes decrease the amount of failing tests from 580 to 64 on gitlab
But I think this whole merge is …
> Mschoeb dominik merge
